"""Prompt text for each learner side, kept in one place so the attacker-voice text lives in
exactly ONE fillable slot.

The harness machinery (harness.py, reflect.py, evolve.py) is side-agnostic. To run the RED
learner you only need to fill the three RED_* strings below with attacker-perspective text
(e.g. generated by GLM 5.3 via OpenRouter) — nothing else changes.

Placeholder rules for the {curly} fields (do not rename them):
  system prompt : {actions} {playbook} {guardrails} {signals} {thresholds}
  reflect prompt: no fields
Keep everything SYMBOLIC: refer only to the fixed game actions against fake nodes. No real
software, CVEs, techniques, or commands.
"""

# ---------------------------------------------------------------------------
# BLUE (defender) — the working, tested version.
# ---------------------------------------------------------------------------
BLUE_SYSTEM = """You are BLUE, the defender in a turn-based SIMULATED network-defense game.
You only see noisy signals, not the attacker's true position. One action per turn.
Detect actions reveal information; respond actions clean up; harden and deceive prevent.
Win by surviving 20 turns or fully evicting the attacker. Protect the crown-jewel database.

ACTIONS:
{actions}

PLAYBOOK:
{playbook}

GUARDRAILS (hard rules, violations are rejected):
{guardrails}

SIGNAL PRIORITY (highest first): {signals}
ALERT THRESHOLDS (ignore weaker signals): {thresholds}

Reply with JSON only: {{"action": "<action>", "target": "<target>", "reason": "<one short sentence>"}}"""

BLUE_PLAYBOOK_V0 = (
    "Look at the strongest signals first. Investigate before responding: confirm a "
    "suspicion with a detect action, then respond on that node. Harden nodes on the "
    "path to the database early. Protect the database above everything else."
)

BLUE_REFLECT_SYSTEM = """You review a finished turn-based SIMULATED network-defense game from BLUE's side.
Write 1-3 short lessons (max 25 words each) that would help Blue win future games at this level.
Lessons must be concrete and reusable: name signals, actions, nodes, or timing. No generic advice.
Reply with JSON only: {"lessons": ["...", "..."]}"""

# ---------------------------------------------------------------------------
# RED (attacker learner) — FILL THESE IN. Structurally identical to the BLUE
# versions above; write them from the attacker's seat, symbolic only.
#   - RED_SYSTEM must keep the same {curly} fields as BLUE_SYSTEM.
#   - RED_PLAYBOOK_V0 is harness v0's strategy text for Red.
#   - RED_REFLECT_SYSTEM mirrors BLUE_REFLECT_SYSTEM but for the attacker.
# See docs/pr-plan.md "PIVOT" for guidance. Leaving these empty raises a clear
# error when LEARNER=red, so the Blue path is unaffected until you fill them.
# ---------------------------------------------------------------------------
# NOTE: these are MINIMAL, mechanical stubs (symmetric to the BLUE_* prompts) so the Red
# learner runs end to end. They intentionally contain NO exploitation strategy — that is what
# GLM 5.3 should generate to make Red actually improve. Keep everything symbolic.
RED_SYSTEM = """You are RED, one player in a turn-based SIMULATED board game on a fake 7-node network.
It is only a game of tokens: "nodes" are dots, an "action" flips a flag with a fixed probability.
Your goal is to reach the crown-jewel database node. One action per turn.

ACTIONS:
{actions}

PLAYBOOK:
{playbook}

RULES YOU MUST FOLLOW:
{guardrails}

Reply with JSON only: {{"action": "<action>", "target": "<node>", "reason": "<one short sentence>"}}"""

RED_PLAYBOOK_V0 = (
    "Move toward the database. Probe a node before committing to it. Prefer nodes you can "
    "already reach, and build on nodes you already hold."
)

RED_REFLECT_SYSTEM = """You review a finished turn-based SIMULATED board game from RED's side.
Write 1-3 short lessons (max 25 words each) that would help Red reach the database faster next time.
Lessons must be concrete and reusable: name actions, nodes, or timing. No generic advice.
Reply with JSON only: {"lessons": ["...", "..."]}"""


SYSTEM_FOR = {"blue": BLUE_SYSTEM, "red": RED_SYSTEM}
PLAYBOOK_V0_FOR = {"blue": BLUE_PLAYBOOK_V0, "red": RED_PLAYBOOK_V0}
REFLECT_SYSTEM_FOR = {"blue": BLUE_REFLECT_SYSTEM, "red": RED_REFLECT_SYSTEM}


def system_for(side: str) -> str:
    tmpl = SYSTEM_FOR.get(side, "")
    if not tmpl:
        raise RuntimeError(
            f"No system prompt for learner side '{side}'. Fill RED_* in backend/prompts.py "
            f"(the attacker-voice text) before running LEARNER={side}."
        )
    return tmpl
